#
# IMPORTANT:
# ---------
# The cron interval must be set to more than 10 seconds
# because the system will set a random delay of 0 to 9 seconds for racing condition avoidance
#
jobs:
  - name: "demo-task"
    description: "execute demo service every 15 seconds"
    cron: "0/15 0/1 * 1/1 * ? *"
    service: "hello.world"
    # optional parameter to tell the service what to do
    parameters:
      hello: "world"
    resolver: "v1.state.resolver"

  - name: "demo-flow"
    description: "execute demo service every 25 seconds"
    cron: "0/25 0/1 * 1/1 * ? *"
    service: "flow://hello-flow"
    # In the demo flow, it has 2 tasks. We use input data mapping to map "db" and "other" parameters accordingly.
    # See "hello-flow.yml for details.
    parameters:
      db:
        host: "db://demo"
        feature: "read only"
      other:
        demo: "some value"
    resolver: "v1.state.resolver"
