site_name: Composable for Java
site_url: https://github.com/accenture/mercury-composable
nav:
    - Home: README.md
    - Methodology: guides/METHODOLOGY.md
    - Getting Started: guides/CHAPTER-1.md
    - Function Execution Strategies: guides/CHAPTER-2.md
    - REST Automation: guides/CHAPTER-3.md
    - Event Script Syntax: guides/CHAPTER-4.md
    - Build, Test and Deploy: guides/CHAPTER-5.md
    - Spring Boot Integration: guides/CHAPTER-6.md
    - Event over HTTP: guides/CHAPTER-7.md
    - Minimalist Service Mesh: guides/CHAPTER-8.md
    - API Overview: guides/CHAPTER-9.md
    - Minimalist Property Graph: guides/CHAPTER-10.md
    - "Appendix I: Application Properties": guides/APPENDIX-I.md
    - "Appendix II: Reserved Names & Headers": guides/APPENDIX-II.md
    - "Appendix III: Actuators, HTTP Client & More": guides/APPENDIX-III.md
    - Release Notes: CHANGELOG.md
    - Design Notes: arch-decisions/DESIGN-NOTES.md
    - Inclusivity: INCLUSIVITY.md
    - Code of Conduct: CODE_OF_CONDUCT.md
    - Contributing: CONTRIBUTING.md
    - Table of Contents: guides/TABLE-OF-CONTENTS.md
plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
theme: readthedocs
