application.name=schema-registry-standalone

# By default, Confluent's local Schema Registry uses 8081
server.port=8081

# REST Automation config
rest.automation=true
web.component.scan=org.platformlambda.helpers.registry
yaml.rest.automation=classpath:/rest.yaml
