/*

    Copyright 2018-2026 Accenture Technology

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

 */

package org.platformlambda.tasks;

import org.platformlambda.core.annotations.PreLoad;
import org.platformlambda.core.models.EventEnvelope;
import org.platformlambda.core.models.TypedLambdaFunction;
import org.platformlambda.core.serializers.SimpleMapper;
import org.platformlambda.core.util.Utility;
import org.platformlambda.mini.kafka.KafkaHeaders;
import org.platformlambda.sync.SyncRuntime;

import java.util.Map;

/**
 * First task of a composable sync-over-async REST facade flow. It registers the cross-pod return route in
 * Redis ({@code begin}) and serializes the request body into the outbound payload, keyed by the
 * correlation-id that will track the round-trip.
 *
 * <h3>Correlation-id sourcing</h3>
 * <p>The correlation-id is supplied via the {@code cid} header in the task's input mapping. The default
 * flow maps {@code model.cid -> header.cid}, where {@code model.cid} is the framework-assigned value: REST
 * automation promotes the first matching trace header (configured via {@code trace.http.header}, e.g.
 * {@code X-Correlation-Id}, {@code X-Trace-Id}, or {@code traceparent} for OTel), or generates a UUID when
 * none is present. This means the inbound trace ID doubles as the correlation-id with no extra config.</p>
 *
 * <p>Deployments that use a proprietary correlation-id header can override this in the flow YAML by
 * replacing (or prepending) the mapping. For example:
 * <pre>
 *   input:
 *     - 'input.header.x-request-id -> header.cid'   # proprietary upstream header
 *     - 'input.body -> *'
 * </pre>
 * </p>
 *
 * <p>It does <b>not</b> publish or wait: the publish is the next task (so a publish failure fails the flow
 * and is rejected to the caller — fail-fast), and the blocking await is the last task (so it runs after
 * the request is on the wire). Sized for user-facing concurrency ({@code instances = 250}); each instance
 * runs on a virtual thread.</p>
 */
@PreLoad(route = "sync.prepare", instances = 250)
public class SyncPrepareTask implements TypedLambdaFunction<Map<String, Object>, EventEnvelope> {

    @Override
    public EventEnvelope handleEvent(Map<String, String> headers, Map<String, Object> input, int instance) {
        // model.cid is the framework-assigned correlation-id (from X-Correlation-Id / X-Trace-Id /
        // traceparent, or a UUID generated by REST automation). The flow maps it here as header.cid.
        String correlationId = headers.getOrDefault("cid", Utility.getInstance().getUuid());
        SyncRuntime.coordinator().begin(correlationId);   // register the return route before publishing
        byte[] payload = SimpleMapper.getInstance().getMapper().writeValueAsBytes(input);
        return new EventEnvelope().setHeader(KafkaHeaders.CORRELATION_ID, correlationId).setBody(payload);
    }
}
